### ISSUE TITLE
Promises

### ISSUE THREAD

**Issue by djorg83** [gold/ttl-localstorage#1]
Why was this implemented with promises? There is nothing async happening.

**Comment by gold** [comment]
The zowie module is implemented without promises.

ttl-localstorage was implemented with promises in case the content for a key was several mb. Some user agents write to local disc immediately; promises can help to overcome potential io inefficiencies.

**Comment by gold** [comment]
Synchronous mode, which is simpler for the developer to use, has been added in v1.5.0. The documentation explains how to do this.
