### ISSUE TITLE
put not handling the exception thrown by the setItem

### ISSUE THREAD

**Issue by sandeep-1983** [gold/ttl-localstorage#3]
Thanks for writing the library, i was about it write one when i searched and found this. As per Storage specs https://developer.mozilla.org/en-US/docs/Web/API/Storage/setItem setItem can throw an Error if storage is full. The 'put' method of base-api.js dont trap the error & this can meant that the promise will never be resolved.

**Comment by gold** [comment]
Thanks for letting me know. Next version I'll address this, hopefully within the next several weeks.
